# Generated by Django 6.0.1 on 2026-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigoCuenta',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
