# Generated by Django 6.0.1 on 2026-01-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_cliente_codigocuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
