# Generated by Django 6.0.1 on 2026-01-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_cliente_dni_remove_cliente_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineacarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
