# Generated by Django 6.0.1 on 2026-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_cliente_ciudad_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigoPostal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
