# Generated by Django 6.0.1 on 2026-01-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='backend.categoria'),
        ),
    ]
