# Generated by Django 6.0.1 on 2026-01-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_categoria_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
