# Generated by Django 6.0.1 on 2026-01-25 19:13

import django.db.models.deletion
from django.db import migrations, models


def limpiar_colecciones(apps, schema_editor):
    """Limpiar los valores de coleccion existentes antes de cambiar a ForeignKey"""
    Producto = apps.get_model('backend', 'Producto')
    Producto.objects.all().update(coleccion=None)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_coleccion'),
    ]

    operations = [
        migrations.RunPython(limpiar_colecciones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.coleccion'),
        ),
    ]
