# Generated by Django 6.0.1 on 2026-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_producto_coleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
