# Generated by Django 6.0.1 on 2026-01-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_banner_enlace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='backend.cliente'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='backend.categoria'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='backend.menu'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoria'),
        ),
    ]
