# Generated by Django 6.0.1 on 2026-01-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_coleccion_options_alter_carritocompra_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoria')),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subcategoria'),
        ),
    ]
