# Generated by Django 6.0.1 on 2026-01-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
