# Generated by Django 6.0.1 on 2026-03-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_producto_subcategoria_delete_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineacarrito',
            name='precio_congelado',
        ),
    ]
