# Generated by Django 6.0.1 on 2026-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_eliminar_precio_congelado_lineacarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
        ),
    ]
