# Generated by Django 6.0.1 on 2026-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_add_porcentaje_iva_to_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
